language: node_js
node_js:

  - "6"
  - "6.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools


script: 
  - jasmine test.js


after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}

